### ISSUE TITLE
服务端与gt5（格雷科技5）好像有冲突

### ISSUE THREAD

**Issue by zqfzqf** [UraniumMC/Uranium#1]
### 测试环境：
服务端：Uranium-1710-stable-4-B15-bundle
MOD：industrialcraft-2-2.2.827-experimental、gregtech-5.09.29
### 产生问题：
![image](https://user-images.githubusercontent.com/33652938/51128810-ba6c4f00-1863-11e9-9cc8-d324e30c23ee.png)
一些基础物品如原石、泥土，堆叠4-7个时就会在一个空位开始新的堆叠，疯狂占背包位置，可以手动堆叠到一起。
**_更换gt的版本（5.09.32p4、5.08.32）还是有这个问题
更换服务端核心（KCauldron-1.7.10-1614.201-bundle）问题消失
所有配置文件均为默认生成，未改动_**

**Comment by xe5700** [comment]
用dev最新版的试试，如果还有问题尝试关闭格雷的统一矿物功能，如果关闭了以后没问题的话我看看。

**Comment by zqfzqf** [comment]
> 用开发最新版的试试，如果还有问题尝试关闭格雷的统一矿物功能，如果关闭了以后没问题的话我看看。

谢谢提醒，开发版210可以正常使用。
