### ISSUE TITLE
Can't start GTNewHorizon ModPack Server

### ISSUE THREAD

**Issue by yukieiji** [UraniumMC/Uranium#3]
Can't start ModPack which can be DL with the following URL
http://downloads.gtnewhorizons.com/#ServerPacks

I tested with Uranium-1710-stable-5-B20-afb7250-server and Uranium-1710-dev-5-B263-72801f9-server.

Clash Report:[crash-2019-04-16_23.03.29-server.txt](https://github.com/UraniumMC/Uranium/files/3085449/crash-2019-04-16_23.03.29-server.txt)
Lastest log:[latest.log](https://github.com/UraniumMC/Uranium/files/3085450/latest.log)
JVM Option:-Xmx4G -Xms4G -XX:+UseShenandoahGC -XX:+UseTLAB -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+UseStringDeduplication -XX:SurvivorRatio=8 -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M -XX:CompressedClassSpaceSize=512M -Xss1G -XX:ParallelGCThreads=12 -XX:ConcGCThreads=3 -Dfile.encoding=UTF-8 -jar Uranium-1710-stable-5-B20-afb7250-server.jar nogui

**Comment by q178666380** [comment]
this caused by invalid item,try update mod GTNewHorizonsCoreMod
