### ISSUE TITLE
WorldEdit Doesn't Work

### ISSUE THREAD

**Issue by Acult** [UraniumMC/Uranium#8]
ERROR LOG: https://pastebin.com/3908Y3d1

I've used the latest Dev build and also tested with B20, in both worldedit doesn't work

**Comment by xe5700** [comment]
Try use latest dev version

**Comment by Acult** [comment]
If you refer to dev 271, I've tried that and same error happens

**Comment by xe5700** [comment]
You can try backup cauldron.yml and rename it then server will generator a new cauldron.yml. This issues is cause by enabled all version of nms remap.

**Comment by Acult** [comment]
Doesnt work, it's like worledit isn't even recognized as plugin

**Comment by RupticMC** [comment]
I don't use Uranium just yet, but on other server softwares... Worldedit 6.1 works just fine.
